version: '3'

services:

  redis:
    image: sample/redis
    container_name: sample-redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
     - 6379:6379
    volumes:
     - ./redis/data:/data